name: Unreal Locres Import

on:
  push:
    branches: [ main ]

jobs:
  import:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run UnrealLocresImport.cmd
        run: scr\UnrealLocresImport.cmd
      - name: Copy Game.locres to scr folder
        run: copy Game.locres scr\Game.locres /y
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Update Game.locres"
          add: "scr\Game.locres"
