name: 生成PAK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检查代码库
      uses: actions/checkout@v2

    - name: CSV文件转换成Locres文件
      run: src\UnrealLocresImport.cmd

    - name: 删除现有的Game.locres
      run: Remove-Item -Path src\Thumper\Content\Localization\Game\en\Game.locres -Force

    - name: 移动生成的Game.locres
      run: move Game.locres src\Thumper\Content\Localization\Game\en\Game.locres

    - name: 提交并推送更新的Game.locres
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src\Thumper\Content\Localization\Game\en\Game.locres
        git commit -m "更新 Game.locres"
        git push

    - name: 打包PAK
      run: |
        src\pack-v11-27.cmd

    - name: 上传Thumper-WindowsNoEditor_p.pak
      uses: actions/upload-artifact@v2
      with:
        name: 中文补丁
        path: src\Thumper-WindowsNoEditor_p.pak
