name: Generate PAK

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Code
      uses: actions/checkout@v2

    - name: Convert CSV file to Locres file
      run: src\UnrealLocresImport.cmd

    - name: Remove existing Game.locres
      run: Remove-Item -Path src\Thumper\Content\Localization\Game\zh-Hans\Game.locres -Force

    - name: Move generated Game.locres
      run: move Game.locres src\Thumper\Content\Localization\Game\zh-Hans\Game.locres

    - name: Commit and push updated Game.locres
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src\Thumper\Content\Localization\Game\zh-Hans\Game.locres
        git commit -m "Update Game.locres"
        git push

    - name: Package PAK
      run: |
        src\pack-v11-27.cmd

    - name: Upload Thumper-WindowsNoEditor_p.pak
      uses: actions/upload-artifact@v3
      with:
        name: Thumper-WindowsNoEditor_p
        path: src\Thumper-WindowsNoEditor_p.pak
