name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  update_and_run_script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run UnrealLocresImport.cmd
      run: src\UnrealLocresImport.cmd

    - name: Remove existing Game.locres
      run: Remove-Item -Path src\Game.locres -Force

    - name: Move generated Game.locres
      run: move Game.locres src\Game.locres

    - name: Commit and push updated Game.locres
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src\Game.locres
        git commit -m "Update Game.locres"
        git push

    - name: Run CMD script
      run: |
        src\pack-v11-27.cmd

    - name: Upload newpak.pak
      uses: actions/upload-artifact@v2
      with:
        name: newpak
        path: src\newpak.pak
