name: Import Locres and Update Game.locres

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 选择 Windows 操作系统

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Run UnrealLocresImport.cmd
      run: src\UnrealLocresImport.cmd  # 运行你的 CMD 脚本

    - name: Remove existing Game.locres
      run: Remove-Item -Path src\Game.locres -Force  # 删除现有的 Game.locres 文件

    - name: Move generated Game.locres
      run: move Game.locres src\Game.locres  # 将生成的 Game.locres 移动到指定位置

    - name: Commit and push updated Game.locres
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src\Game.locres
        git commit -m "Update Game.locres"
        git push
