name: Run CMD script
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run CMD script
        run: |
          scr\v11.27\2\3\UnrealPak.exe scr\..\..\..\newpak.pak -Create=scr\..\..\..\lista.txt -compress
          pause
      - name: Upload newpak.pak
        uses: actions/upload-artifact@v2
        with:
          name: newpak
          path: newpak.pak
